services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: p@ssword123!
      MYSQL_DATABASE: products_db
      MYSQL_USER: user
      MYSQL_PASSWORD: p@ssword123!
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ../database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ../database/init.sql:/docker-entrypoint-initdb.d/init.sql
